### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Dviros** [jevalenciap/iptodomain#3]
Hi,
I'm dealing with a lot of errors which forces me to start again from the last IP.
Is it also possible to make this script use threads and files list in order to run quicker?

Thanks a lot!
Here is the log:

Traceback (most recent call last):
  File "iptodomain.py", line 103, in <module>
    response = urllib.urlopen('%s?%s' % (url, urllib.urlencode(parameters))).read()
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by jevalenciap** [comment]
Since threats can be helpful to run faster, looks like your issue is related to network connectivity.

**Comment by Dviros** [comment]
Dude, Jan 2017..
