### ISSUE TITLE
HTTP error forbidden Issue

### ISSUE THREAD

**Issue by 0xkhaled** [jevalenciap/iptodomain#9]
When I try to use the tool with any input options, it generate the below error. tested on MacOS and Linux

python3 iptodomain.py -l 103.22.201.25 -k 103.22.201.255 -o result.txt -v
Traceback (most recent call last):
  File "/Users/malcrove/Documents/tools/iptodomain/iptodomain.py", line 127, in <module>
    response = urllib.request.urlopen('%s?%s' % (url, urllib.parse.urlencode(parameters))).read()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by smed79** [comment]
The error you're encountering indicates that the response received from the API call is empty (or invalid JSON). 

This typically happens when the API key might be missing, incorrect, or invalid.

Get you free api from VT https://docs.virustotal.com/docs/api-overview
